### ISSUE TITLE
When will this be synced back upstream?

### ISSUE THREAD

**Issue by psi29a** [TES3MP/TES3MP#144]
Is tes3mp in shape to be merge back upstream? :)

**Comment by davidcernat** [comment]
Are you suggesting that all these extensive multiplayer-specific changes should be integrated into OpenMW itself?

**Comment by psi29a** [comment]
Eventually, yes as multiplayer is one of the post 1.0 goals of OpenMW.

I've talked with Koncord in the past and helped him keep his original fork in-sync with OpenMW. I see that you are doing a great job at keeping in sync with upstream which is great! 

We'll have to eventually bite the bullet and think about how best to handle this.

Note: This isn't for now, just pulsing a bit to see where tes3mp is at and where it is going and what will be the level of effort getting this main-lined.

**Comment by davidcernat** [comment]
> Eventually, yes as multiplayer is one of the post 1.0 goals of OpenMW.

Sounds great to me.

However, certain decisions in the structure of tes3mp may not be ideal. Major aspects of OpenMW were not built with multiplayer in mind, such as the saving and loading of stats and world state, and we've had to come up with our own temporary, improvisational approach to them that allows for server-side Lua scripting while affecting the original OpenMW code as little as possible.

Because of that, we should have a group of OpenMW developers going through our code and suggesting ways to bring it in line with their shared vision of a good multiplayer implementation, while adding a number of classes and methods to OpenMW itself that will make the job easier.

> I see that you are doing a great job at keeping in sync with upstream which is great!

Thank you. I've been trying to ensure that staying in sync with OpenMW is effortless. Only changes to the root CMakeLists.txt tend to create merge conflicts, but they are easy enough to fix.

> We'll have to eventually bite the bullet and think about how best to handle this.

An excellent idea. It does feel like the perfect time to start moving in that direction.

> Note: This isn't for now, just pulsing a bit to see where tes3mp is at and where it is going and what will be the level of effort getting this main-lined.

Once tes3mp can be said to be mostly playable – and we're surprisingly close to something like that once we have NPC sync – perhaps we can really focus on that.

**Comment by psi29a** [comment]
I think it best if you popped on to the OpenMW forums with a general tes3mp thread. 

It would be great if you talked about the project there, where you guys currently are in implementation, how you've been developing and handling merge conflicts and how it could possibly conflict with the current code base. This way all the devs are looking of the thread and to the future. If you can, can you explain the client/server architecture?

My long term 'wish', if you will, is to onboard you guys into the OpenMW community so we can move forward in tandem if that is something you guys want. :)

**Comment by Koncord** [comment]
I will be really happy if you (the OpenMW team) separate the mechanics logic into a library
like components. This will boost the quality of tes3mp.

**Comment by psi29a** [comment]
What do you mean by mechanics? That is a very general term.

**Comment by davidcernat** [comment]
Funny how one GitHub issue can lead to an entire forum being created elsewhere. :smile:

Thank you again, psi29a. We'll be going through everything OpenMW can do to help us over in the TES3MP Development forum, one thing at a time.

**Comment by tsilvs** [comment]
If I understand correctly, main concerns are these:

1. OpenMW releases reaching version 1.0
2. TES3MP synching with OpenMW upstream (which has paused on 0.47)
3. Porting TES3MP features back to OpenMW

Where could the progress be publicly tracked?
