### ISSUE TITLE
Chest Inventory Bug

### ISSUE THREAD

**Issue by aaronbannell** [TES3MP/TES3MP#236]
There seems to be a bug when you open chest inventories specificly, once you close the inventory of the chest it will continiously open and close the inventory until you leave the room or relog.

**Comment by davidcernat** [comment]
This hasn't happened to me. Is there a consistent way of reproducing it?

**Comment by davidcernat** [comment]
Seeing as we've had no follow-up on this in a long time, and that – judging by other reports – it seems to be a problem with [a specific mod](https://www.reddit.com/r/tes3mp/comments/828h0f/bug_when_opening_containers/) that also occurs in regular OpenMW, I've gone ahead and closed this issue because it's not something that would be solved from our end anyway.
