### ISSUE TITLE
Can't enter Excise Office in Seyda Neen

### ISSUE THREAD

**Issue by wolfgarr15** [TES3MP/TES3MP#255]
This might have already been reported, or it could be intenetional, but the current version of TES3MP does not allow characters to enter the Census and Excise Office in Seyda Neen. Upon entering the office, the player is immediately bbooted out (teleported to another cell), and a message displays.

This is a problem because it prevents completing a couple quests in the game that require returning to the office.

**Comment by Capostrophic** [comment]
Sorry, but that's sure as hell is intentional - while this chargen technically works, it's very wonky and also resets all stats that were set by the player initially after registering - in less wonky chargen. This is a work-around so people don't report "I went to Benedictius Cumberballa and I lost all my levels, what to do". Did you read the message? It's quite clear.
Until the developers teach Socucius to wait, you aren't supposed to finish Processus Vitelius quest and create your character with his help.

**Comment by ghost** [comment]
AFAIK (could be wrong) you can prevent the chargen scripts from running by setting the global 'chargenstate' to -1.

**Comment by ghost** [comment]
mentioned somewhere else here also. but https://www.nexusmods.com/morrowind/mods/45797 this mod allows entering of chargen area and this script https://github.com/tes3mp-scripts/OriginalStart trys to recreate the chargen at start. while both arent official
