### ISSUE TITLE
Debian server crashes when anyone joins or I hit enter

### ISSUE THREAD

**Issue by 0dot0repeating** [TES3MP/TES3MP#270]
not really sure what else to say about this: whenever I try to host a tes3mp server on 64-bit debian 9, the game crashes the moment someone joins or the moment I hit the enter key

I used the tes3mp-deploy.sh script, and I compiled commit f61664ff so there shouldn't be any incompatibilities there. the only two files I've changed are openmw.cfg (to point to the data files) and tes3-server-default.cfg.

config files, log file: https://gist.github.com/brouzoufman/c1a3f6a2c7e6a05fb7e752a9b76cb479

**Comment by TheCornerclub** [comment]
Revert this commit in PluginExamples:
https://github.com/TES3MP/PluginExamples/commit/cfb952bd9aed980ae70cba461b4a82c7ee3e878e

Or build tes3mp-server from the "0.6.0" branch (probably preferable as that commit is a fix for Linux servers).

**Comment by ghost** [comment]
Revert this commit in PluginExamples:
https://github.com/TES3MP/PluginExamples/commit/cfb952bd9aed980ae70cba461b4a82c7ee3e878e

**Comment by 0dot0repeating** [comment]
the server crashes even with no plugins loaded (`plugins = ` in the server config (edit: or an empty plugin script)) - reverting that commit didn't help either

and compiling the latest commit on the 0.6.0 branch (ac27ca66) still segfaults on hitting enter/player joining

**Comment by ghost** [comment]
You need to have a plugin folder specified.  Something like this, if you used Grim's tes3mp-deploy.sh script. 

``home = /home/tes3mpbuild/keepers/PluginExamples``
``plugins = server.lua``

Are you using that script?  https://github.com/GrimKriegor/TES3MP-deploy

If you're building the master branch to f61664f, revert the PluginExamples commit I linked above.

If you're building the 0.6.0 branch to latest commit, you must replace the version file with that found in the tes3mp 0.6.0 release here on GitHub.  Use the latest commit from PluginExamples without any reverts.  This is the method I used.

**Comment by 0dot0repeating** [comment]
yes, I'm using tes3mp-deploy

I first reverted the pluginexamples commit, then blanked out the plugins config entry (the server has no problems with that - it does have a problem with the config entry missing entirely, but that's not an issue), then had it point to a completely blank lua file. they all crash the same way.

I've compiled f61664ff with the plugin commit reverted, with the plugin commit not reverted, and ac27ca66 with the plugin commit not reverted. they all crash when I hit the enter key - I don't even need someone to join (so the version discrepancy doesn't even have a chance to come up), nor do I need to be pinging the master server.

I'm completely at a loss as to what to do. I was hoping setting the loglevel to 0 would tell me *something*, but it didn't.

**Comment by KevinMichaelDaley** [comment]
I can reproduce this on ubuntu 16.10 (running on my dedicated server box) also in 0.6.0 release branch.  I will try to reproduce it in latest rev. and if I keep seeing it I'll try to debug it.

When I ran it (0.6.0 from build script) in gdb the stacktrace claims there is a segmentation fault in Log::Print function, but I am not sure where exactly because I had yet to switch to a debug build.

I'm working on that now and will keep you posted.

**Comment by 0dot0repeating** [comment]
compiled f61664ff6d with -O0 -g3, and... it's crashing on line 62 of `components/openmw-mp/Log.cpp`?

that's real weird. the logger has to exist at some point (otherwise how would things be logging at all), so that means it's somehow getting destroyed early on? I dunno, I'm not familiar with this code at all, but that's the only reason I can think of for crashing on that line in particular

and looking at what could be destructing it... LOG_QUIT is only in the networking destructor. I have no idea what the bug actually is at this point, but considering it happens when someone joins as well as when I hit the enter key... it looks bad.

https://gist.github.com/brouzoufman/5f0886da0909bd8c6dd62d19e342d2f1

**Comment by KevinMichaelDaley** [comment]
So it seems from the message 
[2017-08-22 00:52:03] [INFO]: Called function "OnServerExit"
[2017-08-22 00:52:03] [ERR]: [Script]: false

that destruction of a Networking object is exactly what is happening.  But this can really only happen if the Main singleton is being accidentally destroyed, which is probably what is happening.  They are doing singletons wrong anyway, in C++11 and higher, the get() function should look like:


const Main& get(){ 
   static Main m;
   return m;
}

in order to be thread-safe and guarantee preservation of the object until program termination.  I am going to try fixing that now, let's see what happens.

**Comment by 0dot0repeating** [comment]
okay, so:

- I moved the LOG_QUIT() out of the networking destructor to after line 333 in main(), which let me actually see what was going on when someone joined. turns out that was the error with the server.lua that reverting the plugin commit solved.

- hitting enter still kills the server, but it says it's quitting peacefully. the `[ERR]: [Script]: false` still appears before it, but that's just OnServerExit - you don't need scripts at all for the enter key to kill the server.

I can avoid hitting the enter key on the server screen, but it's still very odd behaviour. oh well, at least I can host games now.

**Comment by KevinMichaelDaley** [comment]
@brouzoufman's workaround only works when hosting a game from one of the player's machines. 
 Unfortunately, if I run the server on a VPS, and then press enter on the /client/ at any point after joining,  and putting in my name (regardless of what that is) it kills the server with a similar error.  This occurs in any version after 0.6.0 including the latest revision of master.


EDIT:
0x00007ffff5b3d6c8 in Log::print (this=0x0, level=3, hasPrefix=true, file=0x0, line=0, 
    message=0x7ffff84ef4e0 "...MP-deploy/keepers/PluginExamples/scripts/player/json.lua:14: attempt to call field 'GetCaseInsensitiveFilename' (a nil value)
This seems to be where the server is crashing for me.  For some reason, the stacktrace then walks me back to that same line, 62 of Log.cpp.  But the real crash is in the lua code.   
This would appear to indicate that I have an undetected version mismatch between c++ code and lua code due to some weird failure to properly use git (since that function is new) which, it turns out, is indeed the case).

**Comment by 0dot0repeating** [comment]
I'm not hosting on a player's machine, I'm hosting on a linode server. two of us are playing on the server right now with no issue after I reverted that commit and moved the LOG_QUIT into main.

that lua error is what texafornian was talking about; reverting TES3MP/PluginExamples@cfb952b solved that issue for now

**Comment by davidcernat** [comment]
I think it's fair to say that the server crashing when anyone joins is an entirely different issue from the server crashing when you press enter.

The former simply requires you to ensure that the latest commit you use for the Lua scripts repo matches the latest commit you use for the C++ repo. In other words, don't use 3 extra weeks of commits for one expecting it to work with the other.

The server crashing when you press enter is a bit unusual, but doesn't seem like a significant problem.

**Comment by davidcernat** [comment]
According to Koncord, closing the server when pressing Enter is intentional, so I'm going to go ahead and close this issue.
