### ISSUE TITLE
IncreaseSkills Package

### ISSUE THREAD

**Issue by GrimKriegor** [TES3MP/TES3MP#3]
_Originally posted by @Koncord_

**Comment by davidcernat** [comment]
Morrowind and OpenMW keep track of which skills you've increased for a particular level up and give you bonuses to the parent attribute of those skills upon levelling up. For example, increase your Acrobatics 10 times and you get a +5 to your Strength instead of the default +1 if you choose to increase Strength when levelling up.

However, it seems pointless to have a separate packet just for these attribute bonuses (referred to as mSkillIncrease in OpenMW), seeing as they can only possibly change when skills change, and are guaranteed to change whenever skills change naturally (i.e. through regular gameplay instead of script functions).

As a result, I have instead added them to PacketSkill (ID_GAME_SKILL) via 6650b7449809a448e593dba8c62f7252c0ee1794.
