### ISSUE TITLE
Guard Agression State doesn't reset.

### ISSUE THREAD

**Issue by aDudeofDudes** [TES3MP/TES3MP#388]
When I aggro guards via a small theft or attack but don't kill anyone then they stay mad no matter what I do. I can pay gold, go to jail or resist arrest and die then re-spawn but they stay in a semi-agressive state.

They leave me alone but as soon as I talk to any of them they accuse me of my crimes again. 
If I do choose to go to jail then the the gold cost of my fine goes to 0 but they still accuse me of crimes every time I talk to them.

Alternatively if I commit a big crime like "cough" stealing a charged Grand Soul Gem from a mages guild "cough" or anything that causes the guards to have a death warrant out for me. Then they tell me its time to die and kill me and I spawn and they run up and tell me its time to die and kill me again and I spawn and well you get the point.

I just installed a fresh GOTY Edition and TES3MP 0.6.2-hotfixed Windows 64bit 
I'm running the server and playing on it on the same computer.

If this is a repeat I apologies, I just didn't see it on here. I think this project is EPIC level PWN SAUCE and I'm just tryin to be helpful :)

**Comment by davidcernat** [comment]
I am completely unable to replicate your first problem. When I pay off my bounty or go to jail, the bounty gets cleared and guards leave me alone. Are you using the default scripts? Can you do a video recording of it from your perspective?

As for guards still having a death warrant for you when you respawn after committing too large a crime, that's intentional. I do see that, if they're right next to your respawn point, they talk to you before you actually have time to respawn, so I'll go ahead and fix that for version 0.6.3

**Comment by aDudeofDudes** [comment]
It seems I wasted you time my bad. I don't know why but now it seems I cant recreate the loop either where I am constantly asked to pay a bounty of 0 gold...

and the character it was happening too i later committed a larger crime with and is now stuck in a death loop XD

Thanks for the reply though, I'm gonna keep playing around in the game and keep up with whats been posted. If I find anything weird or find myself able to recreate what i mentioned before then Ill make sure to record it next time :)
