### ISSUE TITLE
Add headless server version of TES3MP to Github releases via CI/CD

### ISSUE THREAD

**Issue by rtizzy** [TES3MP/TES3MP#449]
Currently it seems TES3MP must be built if a user desires a headless version of the software for server hosting. 

https://www.reddit.com/r/tes3mp/comments/8major/help_purely_cli_headless_installation/

Adding a headless version to the CI/CD release system seems trivial and would be of use to the community.

**Comment by Koncord** [comment]
Currently server requires some OpenGL and OSG headers to build components (which used in packets).
I have old and not maintaned script to build server for ARM64 with slightly hacked OSG:

https://www.dropbox.com/sh/ydzm724w61f30du/AABHz9cERAGyXNCc8IBKNERMa?dl=0

**Comment by GrimKriegor** [comment]
Headless releases have been available for both arm64 and armhf since the [0.7.0 pre-release](https://github.com/TES3MP/openmw-tes3mp/releases/tag/0.7.0-alpha).

Currently they are prepared via the bloated pipeline that is [TES3MP-deploy](https://github.com/GrimKriegor/TES3MP-deploy), example of a daily build [CI config](https://github.com/GrimKriegor/TES3MP-guar/blob/master/.travis.yml).

It is desirable that we slim down the process and maybe include it in the official pipeline.

EDIT:
There are also [Docker images](https://github.com/TES3MP/server-docker) available for the server
