### ISSUE TITLE
Item charge uses and durability refilled on reconnect

### ISSUE THREAD

**Issue by MushiShirohime** [TES3MP/TES3MP#504]
I am running a server with just me and my friends and I started noticing that my item durability wasn't going down at all
I checked it out and found out that Item durability charge and remaining uses all refill when you exit and rejoin the game
I am unsure whether this is a known bug or if it's only on my end as I couldn't find anyone having a similar issue

**Comment by pongored81** [comment]
Simlar and possibly related to #259 

` [2019-03-31 13:34:14] [WARN]: Unhandled PlayerPacket with identifier 142 has arrived`
I have noticed this as well, and it seems to be an issue with the packet delivery to the player JSON as noted above. It sets the charge count to "-1" for all equipment in inventory on login. I have a single self made mod running. Are you currently using any extra scripts or data files on the server? @AlienJesus

**Comment by MushiShirohime** [comment]
I am not running any scripts or mods

**Comment by JasonGinther** [comment]
I've noticed this issue when hosting a server of my own. I think it's unfortunate that this bug makes the Armorer skill unneeded and effectively useless. Is anyone interested in working on this? Doesn't seem to be assigned, so... how do I sign up? I would be happy to create a pull request for this.

I did some digging around in the lua scripts to see what was going on, and I've learned quite a lot about _why_ this bug occurs, and I think it's worth sharing a high-level overview. Here's what I suspect is "common knowledge" for those who have studied the lua scripts:

1. All player data is saved server-side in JSON files. The data about inventory and equipment is saved in two json objects with the keys "inventory" and "equipment" respectively.
2. The set of all items in the "equipment" section is intended to be a strict subset of the items in the "inventory" section. That is, the inventory holds everything, and the equipment keeps track of which pieces of inventory are equipped to the player's character.
3. Changes to equipment durability and charge (for example when a sword strikes an enemy and its condition decreases) affect the entries as they appear in the "equipment" set but do not affect any entry in the inventory set at that time, I assume for performance reasons.
4. When an equipment item is unequipped, the server-side scripts overwrite one entry in the inventory with the new values of the equipment being unequipped. This is how an equipment item's changes make it into the inventory item's equivalent.
5. When a player logs into a server, that player's character is populated using the equipment to determine what items that character has equipped.

Unfortunately, when an item is equipped, there is no link between that item's "inventory" entry and its "equipment" entry. Instead, the lua scripts try to guess at those relationships, and it's often incorrect. Even though the "equipment" JSON section tells the server what the character has equipped on login, the durability and charge is still populated using values from the "inventory", not from the "equipment" section. In gameplay terms, you the player could pick up a brand new longsword and you could use it until it's nearly broken, but if you never actually unequip that weapon and log out, then logging in again will load the weapon with the durability recorded in the inventory section. Since the inventory never got updated (i.e. longsword was never unequipped), the inventory thinks the longsword is in perfect condition.
Side note, in certain cases, the inventory item will be added to the inventory with a condition of -1, which tes3mp treats as "whatever the maximum condition is for this item because the server scripts don't have that info". So the longsword is loaded with a condition of -1, which gets changed to perfect condition client-side.

There are a ton of consequences to this lack of data, actually, here's another one: if you have two inventory items with identical IDs but different conditions, then equipping one and unequipping it could cause its durability to overwrite the other one's durability in the JSON on the server side. This is because the JSON _doesn't actually know which one of the two items got equipped_ so it just guesses the first inventory item it sees whose ID matches the unequipped item. 

There are two solutions that jump out at me. The first is to add information to the JSON so that it can remember which inventory items correlate to the equipped items. If we have that information, then we can do things like update the inventory entries with the equipment entries' durability and enchantment charge on login or on unequip. This means inventory is always eventually sync'd with equipment. That would address this bug without having to recompile tes3mp, because the changes are only limited to the lua scripts. The second solution (also a lua-only fix) would be to forget about an "equipment" section of the player JSON altogether and just track what inventory items are "equipped" by adding an "equipped" key to inventory entries, where the value is the equipment index that that inventory item occupies. This one _seems_ simpler but it also has performance implications because it would mean that equipment updates like swinging a sword or using a lockpick would mean iterating other players' potentially large inventories every time.

I've implemented the first solution on my personal server. I chose it over the second because the second solution means iterating over O(n) entries in the inventory every single time just to find an equipped inventory item (though I also have thoughts on how to mitigate _that_, for another discussion). I have been testing with it and I believe I every scenario I can think of has been covered. I would be glad to help fix this bug officially by creating a PR. I am a software engineer by daylight, though I admit I'm mostly new to the idea of making contributions to open-source programming projects, so please let me know how I might get started as a contributor or if there's anything a newcomer needs to know on how to start.

**Comment by Nkfree** [comment]
Jason, could you please share the solution you have decided to use with me? I believe David would appreciate PR like this. Would you also care to quote the part where the loaded equipment items charge gets replaced by inventories? LoadEquipment seems to only reach to equipment table, not inventory. Thanks for the insight.

**Comment by JasonGinther** [comment]
@Nkfree, I have created a PR with the proposed change, on the CoreScripts repository. Here is a link to it directly: https://github.com/TES3MP/CoreScripts/pull/85

I have observed on TES3MP version 0.7.0 that the issue where equipment conditions are overwritten by inventory conditions happens when connecting to a server. LoadEquipment will send the correct itemRefIds for equipment, but the condition from the equipment table will be ignored and the client will instead receive that equipment's condition equal to the very first entry in the inventory with the same itemRefId. On the next call to SaveEquipment, the server will read what the condition is and the equipment table will be overwritten with whatever the client sent it back.

We can reproduce that situation easily with the following steps:
1. Create a server with a character, let's call the character "TestDummy"
2. Equip TestDummy with a piece of equipment at max condition, let's say an "iron shortsword" whose max condition is known to be 600
3. In-game, use the sword to hit an enemy and note the condition in-game.
4. Log out from the server as TestDummy and observe TestDummy's player json data in a text editor. Observe that TestDummy's equipment table has an entry for an iron shortsword with with a slightly used condition equal to the noted in-game condition and its inventory table has an iron shortsword with a condition of 600 (or possibly -1, which is equal to max condition for the item)
6. Log back into the server as TestDummy and observe the condition of the iron shortsword. The condition should match what was in the equipment table, and should be slightly used, but it instead matches the inventory.
7. Log out of the server and edit TestDummy's inventory table so the iron shortsword now has 111 condition. Do not edit the equipment table.
8. Log in and observe that the iron shortsword's condition is 111, despite what the condition in the equipment table was. The equipment table in the JSON will also be overwritten with a condition of 111 the moment the SaveEquipment lua function is called.

I think it's worth noting that the issue where equipment is given inventory's condition on login may be a client-side issue or maybe in the server compiled code, but it doesn't answer the question of when or how the conditions recorded in the equipment table are intended to be written into the inventory table. If a player uses a sword then unequips it before logging out, how does that information get into the inventory where it's supposed to go? I believe the PR answers all these questions without having to change compiled code (regardless of whether or not there's a bug in the way the compiled code reads equipment values on login).

**Comment by Nkfree** [comment]
Thank you, Jason, for this comprehensive explanation. 

I've already known how to reproduce it, what I was interested in is the last paragraph where you mention that you don't know whether it's server code related or clientside issue. 

I have made a short script (without affecting original server files) that saves the equipment and affects inventory entries as well. It only serves it's purpose if there is just one item per refId in the inventory. If there's say two or more iron swords the problem that you have described occurs. I will play with it but I don't see myself coming up with a simple or any solution, thank you anyway for your approach.
