### ISSUE TITLE
Getting the console

### ISSUE THREAD

**Issue by Testing12304** [TES3MP/TES3MP#583]
Many players manage to get the console on the server. How do they do it? And how to deal with it.

**Comment by testman42** [comment]
Are you the owner of the server or are you just playing on it?

Server owners have few ways to regulate who gets access to the developer console.
Read through [this guide](https://steamcommunity.com/groups/mwmulti/discussions/1/133258593388999187/) to get a detailed description of how server management is done.
But a quick overview of access to the console:
* `config.allowConsole` in config.lua determines if players have access to console by default
* `"consoleAllowed"` in the `"settings"`section of player's .json file determines console access for that player specifically
* admin can use `/setconsole` server command in order to change console access for any of the players who are logged in to the server
