### ISSUE TITLE
TES3MP on Fedora 34 (Solved!)

### ISSUE THREAD

**Issue by CoconutGirl25** [TES3MP/TES3MP#585]
Hello,

I have Fedora 34 and am trying to install TES3MP.  I am not proficient at Linux, so please bare with me.  I have the folder in my system, but the file will not execute.  /home/user/TES3MP-deploy/tes3mp-deploy.sh

Can someone help me?  I can get around with the right commands, I have scoured the internet to try and find other Fedora users having this issue, but it seems there are none.  I do have Open MW already and the game opens, just having issues getting TES3MP to work.

Thank you!

**Comment by testman42** [comment]
TES3MP-deploy is for compiling from source. You don't need to do that, there is an already prepared [Linux release](https://github.com/TES3MP/openmw-tes3mp/releases/download/0.7.0-alpha/tes3mp-GNU+Linux-x86_64-release-0.7.0-alpha-abc4090a0f-01d297f5c6.tar.gz).

Since you say that you are not yet proficient with Linux, you will probably encounter some more obstacles. It will help if you learn how to look up solutions for such problems on the internet, and such skill will be useful in many other situatuons as well. Also feel free to join [TES3MP Discord ](https://discord.gg/ECJk293) and politely ask in #technical_help channel for someone to guide you through the process of setting it up.

**Comment by CoconutGirl25** [comment]
I actually realized I am a complete idiot and got it working from the link you sent.  I had used that link and file folder before I had opened this query, but what I thought looked like an executable icon was not what I should have clicked on.  It was the paper with the same icon on the sheet directly next to it that I should have been using!  Usually I am pretty good at finding solutions, but this is not as common of an issue to have vs. other Linux issues.  I am also new to Fedora, this is my 4th distro in 3 years.  My PC has a tenancy to eat operating systems.  Hard to get proficient when you have to change so often.  LOL.  

Thanks!
