### ISSUE TITLE
Caius Cosades disappears

### ISSUE THREAD

**Issue by pxsxs** [TES3MP/TES3MP#605]
I have already finished the quests given by Caius Cosades, but my friend has not.
When my friend enters Caius' house, he is there and everything is fine. But when I enter the cell Caius disappears in front of our eyes.

this probably affects in other similar situations with NPCs as well.

**Comment by testman42** [comment]
> I have already finished the quests given by Caius Cosades, but my friend has not.

As in, you are playing with journal sync disabled?

Isn't this exactly what was warned about in the Frequently Asked Questions?

> However, Morrowind's quest logic and NPC dialogue is built around the existence of a single player. As a result, the vast majority of questlines will break very quickly if their states are not shared across players.

**Comment by davidcernat** [comment]
Sounds like you don't have journals shared. This is not a bug, it's the game's singleplayer-oriented quest logic. TES3MP's scope doesn't extend to modifying quests so that unshared journals work fine by default.

If you want to get around this somewhat elegantly, use different cell instances of his house for each player.

**Comment by pxsxs** [comment]
ok, I thought it was a problem related to not respecting the initial load of the cell, given by the first player to enter.
and yes, journals shared is disabled.
