### ISSUE TITLE
linux error attempt to call field 'encode_empty_table_as_object' (a nil value)"

### ISSUE THREAD

**Issue by demosthenesk** [TES3MP/TES3MP#609]
i use ubuntu 20.04 lts and i get these errors when try to run the server:

Loading server config from the package directory
Loading settings file: /home/user/Bin/TES3MP-server/tes3mp-server-default.cfg
[2022-03-19 12:38:00] [INFO]: TES3MP dedicated server 0.8.0 (Linux 64-bit)
Protocol version: 9
Oldest compatible commit hash: 000e8724ca

[2022-03-19 12:38:00] [ERR]: Lua script ./server/scripts/serverCore.lua error (2): "./server/lib/lua/jsonInterface.lua:9: attempt to call field 'encode_empty_table_as_object' (a nil value)"
terminate called after throwing an instance of 'std::runtime_error'
  what():  Lua script ./server/scripts/serverCore.lua error (2): "./server/lib/lua/jsonInterface.lua:9: attempt to call field 'encode_empty_table_as_object' (a nil value)"
./tes3mp-server: line 7: 107259 Aborted                 (core dumped) LD_LIBRARY_PATH="./lib" ./tes3mp-server.x86_64 "$@"

**Comment by testman42** [comment]
Can not reproduce, with neither server-only release or with standard release

Current solution to this issue is to edit the `server/lib/lua/jsonInterface.lua` file where you change the third line from
```lua
 local cjsonExists = doesModuleExist("cjson")
```
into
```lua
local cjsonExists = false
```
or, if you are absolutely sure that you do not need it for anything else, you could try removing the `lua-cjson` package from your system by using the distribution's package manager.

**Comment by demosthenesk** [comment]
i removed lua-cjson module from synaptic.
now it works without it.
Thanks !
