### ISSUE TITLE
Working MacOS release.

### ISSUE THREAD

**Issue by jiri-psenicka** [TES3MP/TES3MP#680]
Are there any plans for official release of MacOS version?

I tried to use tes3mp-mac-pkg but it doesn't work at all, I don't see any servers and am unable to interact with server browser window anyhow. Launch via openMW isn't possible as there's no such option.

Author of tes3mp-mac-pkg says it can't be a problem related to MacOS port and only says "Check out the Getting Started section on https://tes3mp.com/" which I did and those troubles aren't covered here anywhere.

**Comment by backlabs1** [comment]
I might be able to work on a macOS release if someone can provide information about how to get a working virtual machine image. (I don't know whether that's possible without a purchase. I don't have any macOS hardware and I'm not interested in purchasing anything.)

**Comment by backlabs1** [comment]
Adding a link to the corresponding tes3mp-mac-pkg issue: <https://github.com/samkaufman/tes3mp-mac-pkg/issues/1>

**Comment by jiri-psenicka** [comment]
You can run latest MacOS in vmware, but I tried before and it isn't a best experience when talking about performance. I don't know if it's sufficient for development and testing purposes.

**Comment by backlabs1** [comment]
Okay. Performance may not matter for work on packaging. Where can I get the installer ISO image or virtual machine image? Does Apple make it available for download?

**Comment by jiri-psenicka** [comment]
They do, but you need Mac with Appstore to download it directly. There is however reupload on archive.org

[https://archive.org/details/Sonoma.iso](https://archive.org/details/Sonoma.iso)

**Comment by davidcernat** [comment]
Try this one:

https://github.com/samkaufman/tes3mp-mac-pkg/releases/tag/v0.8.1-0

**Comment by jiri-psenicka** [comment]
> Try this one:
> 
> https://github.com/samkaufman/tes3mp-mac-pkg/releases/tag/v0.8.1-0

Sadly it doesn't work. At least in my case and under Sonoma not.

**Comment by jiri-psenicka** [comment]
> @jiri-psenicka, thanks for the link.

I have one Mac Mini (last intel model) I am about to sell. If virtual machine isn't sufficient for any reason, I can postpone selling this machine and provide you with remote access to real HW for up to few weeks instead. It's the least I can do to contribute a little.

**Comment by backlabs1** [comment]
@jiri-psenicka,

>provide you with remote access to real HW for up to few weeks

Thanks for the offer, but I would need ongoing hardware availability rather than for just a few weeks. If this stuff was just "fix once and forget" then the release would already be working for you (unless the problem happens to be something on your end). For example, releases may require testing/development on each of the supported versions of macOS, plus new macOS releases, plus new TES3MP releases, etc. Hopefully a virtual machine is adequate.

Since the two issues you opened have been closed, and if you may be available to help with testing on macOS, please consider leaving a comment at <https://codeberg.org/backlabs1/TES3MP/issues/1> so we can continue discussion there.
